// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using f1_portal_api.DataAccess;

#nullable disable

namespace f1_portal_api.DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260309192505_initial-migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("f1_portal_api.Domain.TicketsByPurchaseDate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("PurchaseDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TicketCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseDate")
                        .IsUnique();

                    b.ToTable("TicketsByPurchaseDate");
                });

            modelBuilder.Entity("f1_portal_api.Domain.TicketsByRaceDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("RaceDayDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RaceDayId")
                        .HasColumnType("bigint");

                    b.Property<string>("RaceDayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TicketCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RaceDayId")
                        .IsUnique();

                    b.ToTable("TicketsByRaceDay");
                });
#pragma warning restore 612, 618
        }
    }
}
